Wrote/copied PostQuestionAnswers in ApiHelper
NDacevic/TestApp_Grupp3 pull request #49
Opened 2020-05-23 09:59 UTC by mikaelollhage

2020-05-23 11:36 UTC, NDacevic commented on TestApp/TestApp/ApiHelper.cs
> +                    await new MessageDialog("Provet har sparats").ShowAsync();
"provet har sparats" == "Frågan har sparats"

2020-05-23 11:37 UTC, NDacevic requested changes
Det står fel bekräftelsemeddelande när frågan är sparad

2020-05-24 17:57 UTC, JohnnyKrook submitted a review, later dismissed

2020-05-25 07:53 UTC, NDacevic approved these changes

2020-05-25 07:53 UTC, merged